### ISSUE TITLE
SyntaxError: Invalid regular expression: /[/: Unterminated character class

### ISSUE THREAD

**Issue by popenkomaksim** [automaidan/judges#38]
We should filter user input in search input.
Avoid / [ ] etc.
http://prosud.info/#/search/

```
vendor-9d3bd80e89.js:22009 SyntaxError: Invalid regular expression: /[/: Unterminated character class
    at RegExp (native)
    at http://prosud.info/scripts/app-6b7d2674cb.js:3:4002
    at Array.filter (native)
    at t.search (http://prosud.info/scripts/app-6b7d2674cb.js:3:3976)
    at fn (eval at compile (http://prosud.info/scripts/vendor-9d3bd80e89.js:34:21506), <anonymous>:4:233)
    at p.$eval (http://prosud.info/scripts/vendor-9d3bd80e89.js:33:6539)
    at http://prosud.info/scripts/vendor-9d3bd80e89.js:35:8279
    at http://prosud.info/scripts/vendor-9d3bd80e89.js:35:14502
    at o (http://prosud.info/scripts/vendor-9d3bd80e89.js:31:829)
    at $$writeModelToScope (http://prosud.info/scripts/vendor-9d3bd80e89.js:35:14461)
```

**Comment by popenkomaksim** [comment]
Works like a charm.

```
function escapeRegExp(str) {
    if (!_.isString(str)) {
        return "";
    }
    return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
```

**Comment by popenkomaksim** [comment]
Fixed in PR https://github.com/automaidan/judges/pull/50
